/**************************************************************************
* combine.sas
*
* Concatenate the individual OUT* datasets generated by hiv_synthesis.sas
* into one dataset for create_wide_file.sas.
**************************************************************************/

%let sasoutputdir = %scan(&sysparm,1," ");
libname a "&sasoutputdir/";

data a.concatenated_data(compress=binary);
    set a.out:;
run;
