/**************************************************************************
* combine.sas
*
* Concatenate the individual OUT* datasets generated by hiv_synthesis.sas
* into one dataset for create_wide_file.sas.
*
* The KEEP= list contains source variables required by the active code in
* create_wide_file.sas. Variables created within create_wide_file.sas are
* deliberately not carried forward unless they are also source variables.
*
*
* The single SET + KEEP= approach should reduce the size of the combined
* dataset and simplify the workflow.
**************************************************************************/

%let sasoutputdir = %scan(&sysparm,1," ");
libname a "&sasoutputdir/";

data a.concatenated_data(compress=binary);
    set a.out:
        (keep=

        /* Identifiers */
        run
        cald
        option

        /* Model parameters */
        inc_cat
        prob_sbp_increase
        sbp_cal_eff
        rr_cvd_tx
        rr_cvd_tx_effective
        prob_htn_link
        rr_cost_lowqual_cvdcare
        p_hard_reach_w
        p_hard_reach_m
        hard_reach_higher_in_men

        /* Age groups */
        s_ageg1517m
        s_ageg1517w
        s_ageg1819m
        s_ageg1819w
        s_ageg2024m
        s_ageg2024w
        s_ageg2529m
        s_ageg2529w
        s_ageg3034m
        s_ageg3034w
        s_ageg3539m
        s_ageg3539w
        s_ageg4044m
        s_ageg4044w
        s_ageg4549m
        s_ageg4549w
        s_ageg5054m
        s_ageg5054w
        s_ageg5559m
        s_ageg5559w
        s_ageg6064m
        s_ageg6064w
        s_ageg6569m
        s_ageg6569w
        s_ageg7074m
        s_ageg7074w
        s_ageg7579m
        s_ageg7579w
        s_ageg8084m
        s_ageg8084w
        s_ageg85plm
        s_ageg85plw

        /* Population / mortality */
        s_dead_allcause_ge18
        s_dead_cvd
        s_dead_cvd_2544
        s_dead_cvd_3039m
        s_dead_cvd_3039w
        s_dead_cvd_4049m
        s_dead_cvd_4049w
        s_dead_cvd_4564
        s_dead_cvd_5059m
        s_dead_cvd_5059w
        s_dead_cvd_6069m
        s_dead_cvd_6069w
        s_dead_cvd_7079m
        s_dead_cvd_7079w
        s_dead_cvd_ge18
        s_dead_cvd_ge65
        s_dead_cvd_ge80m
        s_dead_cvd_ge80w
        s_dead_ddaly
        s_dead_hivneg_anycause
        s_dead_hivneg_anycause_ge18
        s_dead_hivneg_cvd_ge18
        s_dead_hivpos_anycause
        s_dead_hivpos_anycause_ge18
        s_dead_hivpos_cvd_ge18

        /* HIV outcomes and status */
        s_hiv1519m
        s_hiv1519w
        s_hiv1564m
        s_hiv1564w
        s_hiv1819m
        s_hiv1819w
        s_hiv2024m
        s_hiv2024w
        s_hiv2529m
        s_hiv2529w
        s_hiv3034m
        s_hiv3034w
        s_hiv3539m
        s_hiv3539w
        s_hiv4044m
        s_hiv4044w
        s_hiv4549m
        s_hiv4549w
        s_hiv5054m
        s_hiv5054w
        s_hiv5559m
        s_hiv5559w
        s_hiv6064m
        s_hiv6064w
        s_hiv6569m
        s_hiv6569w
        s_hiv7074m
        s_hiv7074w
        s_hiv7579m
        s_hiv7579w
        s_hiv8084m
        s_hiv8084w
        s_hiv85plm
        s_hiv85plw

        /* Life years and DALYs */
        s_dly
        s_live_ddaly
        s_ly

        /* Costs */
        s_d_t_adh_int_cost
        s_dadc_cost
        s_dart_cost
        s_dcd4_cost
        s_dcost_3tc
        s_dcost_child_hiv
        s_dcost_circ
        s_dcost_condom_dn
        s_dcost_dar
        s_dcost_dol
        s_dcost_drug_level_test
        s_dcost_efa
        s_dcost_lpr
        s_dcost_nev
        s_dcost_prep_ac_adh
        s_dcost_prep_inj
        s_dcost_prep_oral
        s_dcost_prep_visit_inj
        s_dcost_prep_visit_oral
        s_dcost_sw_program
        s_dcost_switch_line
        s_dcost_taz
        s_dcost_ten
        s_dcost_zdv
        s_dcot_cost
        s_dfull_vis_cost
        s_dnon_tb_who3_cost
        s_dres_cost
        s_dtb_cost
        s_dtest_cost
        s_dvis_cost
        s_dvl_cost
        s_htn_cost_clin
        s_htn_cost_cvd
        s_htn_cost_drug
        s_htn_cost_scr

        /* Hypertension / systolic BP */
        s_htn_over_dx_ge18
        s_sbp_2529m
        s_sbp_2529w
        s_sbp_3034m
        s_sbp_3034w
        s_sbp_3539m
        s_sbp_3539w
        s_sbp_4044m
        s_sbp_4044w
        s_sbp_4549m
        s_sbp_4549w
        s_sbp_5054m
        s_sbp_5054w
        s_sbp_5559m
        s_sbp_5559w
        s_sbp_6064m
        s_sbp_6064w
        s_sbp_6569m
        s_sbp_6569w
        s_sbp_7074m
        s_sbp_7074w
        s_sbp_7579m
        s_sbp_7579w
        s_sbp_ge80m
        s_sbp_ge80w
        s_sbp_max_over_ge18
        s_sbp_over_ge18

        /* IHD / CVA incidence and prevalence */
        s_cva_inc_all_modsev_2544
        s_cva_inc_all_modsev_4049m
        s_cva_inc_all_modsev_4049w
        s_cva_inc_all_modsev_4564
        s_cva_inc_all_modsev_5059m
        s_cva_inc_all_modsev_5059w
        s_cva_inc_all_modsev_6069m
        s_cva_inc_all_modsev_6069w
        s_cva_inc_all_modsev_7079m
        s_cva_inc_all_modsev_7079w
        s_cva_inc_all_modsev_ge18m
        s_cva_inc_all_modsev_ge18w
        s_cva_inc_all_modsev_ge65
        s_cva_inc_all_modsev_ge80m
        s_cva_inc_all_modsev_ge80w

        s_cva_prev_4049m
        s_cva_prev_4049w
        s_cva_prev_5059m
        s_cva_prev_5059w
        s_cva_prev_6069m
        s_cva_prev_6069w
        s_cva_prev_7079m
        s_cva_prev_7079w
        s_cva_prev_ge18m
        s_cva_prev_ge18w
        s_cva_prev_ge80m
        s_cva_prev_ge80w

        s_ihd_inc_all_modsev_2544
        s_ihd_inc_all_modsev_4049m
        s_ihd_inc_all_modsev_4049w
        s_ihd_inc_all_modsev_4564
        s_ihd_inc_all_modsev_5059m
        s_ihd_inc_all_modsev_5059w
        s_ihd_inc_all_modsev_6069m
        s_ihd_inc_all_modsev_7079m
        s_ihd_inc_all_modsev_7079w
        s_ihd_inc_all_modsev_6069w
        s_ihd_inc_all_modsev_ge18m
        s_ihd_inc_all_modsev_ge18w
        s_ihd_inc_all_modsev_ge65
        s_ihd_inc_all_modsev_ge80m
        s_ihd_inc_all_modsev_ge80w

        s_ihd_prev_4049m
        s_ihd_prev_4049w
        s_ihd_prev_5059m
        s_ihd_prev_5059w
        s_ihd_prev_6069m
        s_ihd_prev_6069w
        s_ihd_prev_7079m
        s_ihd_prev_7079w
        s_ihd_prev_ge18m
        s_ihd_prev_ge18w
        s_ihd_prev_ge80m
        s_ihd_prev_ge80w

        );
run;