


keep cald  s_alive_m  s_alive_w  s_primary1549 s_alive1549 s_hiv1549   s_hiv1549w   s_hiv1549m  s_alive1549_w  s_alive1549_m  option s_hiv1564 discount
run s_pregnant_oth_dol_adv_birth_e s_pregnant s_pregnant_not_diagnosed_pos s_m_1524_newp  s_m_2534_newp s_m_3544_newp s_m_4554_newp s_m_5564_newp 
s_w_1524_newp  s_w_2534_newp  s_w_3544_newp s_w_4554_newp s_w_5564_newp s_i_age1_m_newp s_i_age2_m_newp s_i_age3_m_newp s_i_age4_m_newp 
s_i_age5_m_newp s_i_age1_w_newp s_i_age2_w_newp s_i_age3_w_newp s_i_age4_w_newp s_i_age5_w_newp  s_dead_ddaly  s_live_ddaly  s_dead_daly  
s_live_daly  s_dead_ddaly_ntd  s_dead_ddaly_oth_dol_adv_birth_e  s_ddaly_mtct s_ddaly_non_aids_pre_death s_dcost_zdv s_dcost_ten 
s_pop_wide_tld_prep_elig  s_pop_wide_tld_prep  s_prep_oral_willing s_prep_any_willing
s_dcost_3tc  s_dcost_nev s_dcost_lpr s_dcost_dar s_dcost_taz s_dcost_efa s_dcost_dol s_dart_cost s_dcost_prep_oral s_dcost_prep_inj s_dcost_prep_visit
s_dcost_prep_ac_adh s_dcost_circ s_dcost_condom_dn s_dcost_prep_visit_oral s_dcost_prep_visit_inj s_dvis_cost s_pop_wide_tld_as_art
s_dart_1_cost s_dart_2_cost s_dart_3_cost s_dart_cost s_dvl_cost s_dcd4_cost s_dadc_cost s_dnon_tb_who3_cost s_dtb_cost s_dtest_cost s_dcot_cost 
s_dres_cost s_d_t_adh_int_cost  s_dcost_prep_inj  s_dcost_prep_oral  s_dcost_prep_visit  s_dcost_prep_visit_inj  s_dcost_prep_visit_oral  	 
s_dcost_prep_ac_adh s_dcost_avail_self_test s_cost_avail_self_test s_dcost_non_aids_pre_death s_dcost_non_aids_pre_death  s_dfull_vis_cost s_dcost_circ  s_dcost_condom_dn  
s_dcost_switch_line s_dcost_drug_level_test s_dcost_child_hiv  s_ai_naive_no_pmtct_c_nnm_  s_ai_naive_no_pmtct_c_pim_  s_ai_naive_no_pmtct_e_inm_ 
s_ai_naive_no_pmtct_c_rt184m_  s_ai_naive_no_pmtct_c_rt65m_ s_ai_naive_no_pmtct_c_rttams_ s_mcirc_1519m  s_mcirc_2024m  s_mcirc_2529m  s_mcirc_3034m  
s_mcirc_3539m s_mcirc_4044m  s_mcirc_4549m s_mcirc_3034m  s_mcirc_3539m s_mcirc_4044m  s_mcirc_4549m  s_hiv1519m  s_hiv2024m  s_hiv1519w  s_hiv2024w  
s_hiv1564m   s_hiv6569m   s_hiv7074m   s_hiv7579m   s_hiv8084m   s_hiv85plm  s_hiv1564w   s_hiv6569w   s_hiv7074w   s_hiv7579w   s_hiv8084w   s_hiv85plw  
s_hiv6569m   s_hiv7074m   s_hiv7579m   s_hiv8084m   s_hiv85plm  s_hiv6569w   s_hiv7074w   s_hiv7579w   s_hiv8084w   s_hiv85plw  s_ageg6569m  s_ageg7074m
s_ageg7579m  s_ageg8084m  s_ageg85plm  s_ageg6569w  s_ageg7074w  s_ageg7579w  s_ageg8084w  s_ageg85plw  s_onart_m5054_  s_onart_m5559_  s_onart_m6064_  
s_onart_m6569_	 s_onart_m7074_  s_onart_m7579_  s_onart_m8084_  s_onart_m85pl_	 s_onart_w5054_  s_onart_w5559_  s_onart_w6064_  s_onart_w6569_	 
s_onart_w7074_  s_onart_w7579_  s_onart_w8084_  s_onart_w85pl_	s_alive1564_w  s_alive1564_m  s_m_newp s_w_newp  s_infection_pre_year_interv 
s_infection_post_year_interv   s_death_hiv_inf_pre_year_interv   s_death_hiv_inf_post_year_interv s_newp_ge1 s_newp_ge5 s_newp s_newp_sw s_sw_newp_cat2  
s_sw_newp_cat3 s_sw_newp_cat4 s_sw_newp_cat5  s_w1549_newp_ge1 s_m1549_newp_ge1 s_m1549_newp_ge1 s_alive1549_m s_w1549_newp_ge1 s_alive1549_w
s_m1524_newp_ge1  s_m1524_newp_ge1 s_ageg1517m s_ageg1819m  s_ageg1519m s_ageg2024m s_ageg1517w s_ageg1819w s_ageg1519w s_ageg2024w  s_newp_ge5 
s_ep  s_npge2_l4p_1549m  s_npge2_l4p_1549w  s_sw_1564  s_sw_1549  s_sw_newp   s_tested_m s_tested_f s_tested_sw s_tested s_mcirc_1549m
s_diag_this_period s_year_1_infection_diag  s_year_1_infection s_tested_4p_m1549_ s_diag_m1549_ s_tested_4p_w1549_  s_diag_w1549_
s_mcirc s_mcirc_1519m s_mcirc_2024m s_mcirc_2529m s_mcirc_3034m s_mcirc_3539m s_mcirc_4044m s_mcirc_4549m  s_i_m_newp s_i_w_newp  s_sw_1549   s_ever_sw s_sw_program_visit  s_hiv_sw 
s_hiv_cab_3m  s_hiv_cab_6m  s_hiv_cab_9m  s_hiv_cab_ge12m  s_newp_this_per_hivneg_m_prep  s_newp_this_per_hivneg_w_prep s_prep_any s_onprep_m 
s_onprep_w  s_prep_any_elig_past_year s_prep_any_elig_past_5year  s_prep_newp s_prep_newpg1  s_prep_newpg2  s_prep_newpg3  s_prep_newpg4
s_newp_this_per_prep  s_newp_this_per_hivneg s_prep_any_elig  s_pop_wide_tld_prep_elig s_prep_newp  s_newp_hivneg s_all_prep_criteria 
s_all_prep_criteria_hivneg  s_prep_elig_hivneg s_prep_elig_hivneg_onprep s_prep_elig_onprep_inj s_hiv1_prep_any s_onprep_1524w   s_onprep_sw 
s_prep_oral s_prep_inj  s_pep_not_prep  s_pop_wide_tld_prep s_prep_any_ever  s_elig_prep_any_w_1524  s_elig_prep_any_w_2534 s_elig_prep_any_w_3544  
s_prep_any_w_1524  s_prep_any_w_2534 s_prep_any_w_3544 s_prep_oral_effect_non_res_v  s_onart s_onart_as_tld_prep s_prep_adhg80  
s_currently_in_prep_inj_tail s_em_inm_res_o_cab_off_3m  s_emerge_inm_res_cab_tail s_prep_inj_ever s_em_inm_res_o_cab_off_3m  s_emerge_inm_res_cab_tail 
s_prep_inj_ever_hiv  s_em_inm_res_o_cab_off_3m s_em_inm_res_o_cab_off_3m  s_emerge_inm_res_cab_tail s_em_inm_res_o_cab_off_3m_pr  
s_emerge_inm_res_cab_tail_pr  s_prep_inj_reinit_prim_res s_prep_inj_init_prim s_prep_inj_reinit_prim_res s_prep_inj_init_prim_res 
s_prep_inj_reinit_prim s_prep_inj_init_prim  s_em_inm_res_o_cab_off_3m   s_o_cab_or_o_cab_tm1_no_r s_em_inm_res_o_cab_off_3m_npr 
s_o_cab_or_o_cab_tm1_no_r  s_o_cab_or_o_cab_tm1_no_r_prim s_cab_res_emerge_primary s_emerge_inm_res_cab_tail_pr  s_cur_in_prep_inj_tail_prim   
s_prep_inj_reinit_prim_res  s_prep_inj_init_prim_res  s_emerge_inm_res_cab_tail s_cur_in_prep_inj_tail_no_r s_cab_res_prep_inj_primary 
s_prep_inj_inf_or_off_3m s_infected_inm  s_prep_primary_prevented  s_primary  s_cab_res_primary s_prep_any_start  s_prep_oral_start s_prep_inj_start  
s_prep_vr_start s_start_restart_prep_inj s_start_restart_prep_inj_prim  s_start_restart_prep_inj_hiv s_start_rest_prep_inj_hiv_cabr 
s_start_rest_prep_inj_prim_cabr s_em_inm_res_o_cab  s_hiv1_prep_any  s_hiv1_prep_oral  s_hiv1_prep_inj s_hiv1_prep_any 
s_infected_on_prep_inj  s_em_inm_res_o_cab  s_start_rest_prep_inj_hiv_cabr  s_em_inm_res_o_cab_off_3m s_started_prep_inj_hiv  s_started_prep_any_hiv 
s_tot_yrs_prep_oral_gt_5  s_tot_yrs_prep_inj_gt_5 s_prep_oral_ever  s_prep_inj_ever  s_prep_primary_prevented  s_prep_primary_prevented 
s_prep_reinit_primary  s_prep_init_primary  s_prep_primary_prevented s_cab_res_o_cab  s_cab_res_tail  s_cab_res_primary s_cur_res_cab
s_diagprim_prep_inj s_prep_inj_at_infection  s_diagprim_prep_inj s_hiv_cab_3m  s_hiv_cab_6m  s_hiv_cab_9m  s_hiv_cab_ge12m 
s_hiv_cab s_emerge_inm_res_cab  s_switch_prep_from_oral  s_switch_prep_from_inj  s_switch_prep_to_oral s_switch_prep_to_inj 
s_cur_res_cab  s_iime_  s_pop_wide_tld_hiv  s_pop_wide_tld_prep  s_pop_wide_tld_hiv  s_pop_wide_tld_prep_elig  s_pop_wide_tld_prep_elig  
s_pop_wide_tld_neg_prep_inelig  s_hiv1549m  s_hiv1549w  s_hiv_pregnant  s_hiv1549   
s_primary1549w  s_hiv1549w  s_primary1549m  s_hiv1549m  s_primary1519w   s_primary2024w s_primary1519m s_primary2024m 
s_primary2529w  s_primary3034w s_primary2529w s_primary3034w  s_primary2529m s_primary3034m    s_primary3539w  s_primary4044w s_primary3539m 
s_primary4044m  s_primary4549w  s_primary5054w  s_primary4549m  s_primary5054m   s_primary5559w  s_primary6064w s_primary5559m  s_primary6064m
s_primary_sw s_primary_prep  s_hiv1519w   s_ageg1519w  s_hiv1519m   s_ageg1519m   s_hiv2024w   s_ageg2024w  s_hiv2024m   s_ageg2024m  s_hiv2529w   
s_ageg2529w  s_hiv2529m   s_ageg2529m  s_hiv3034w   s_ageg3034w  s_hiv3034m   s_ageg3034m s_hiv3539w   s_ageg3539w s_hiv3539m   s_ageg3539m 
s_hiv4044w   s_ageg4044w  s_hiv4044m   s_ageg4044m  s_hiv4549w   s_ageg4549w  s_hiv4549m   s_ageg4549m s_hiv5054w   s_ageg5054w  s_hiv5054m   
s_ageg5054m  s_hiv5559w   s_ageg5559w  s_hiv5559m   s_ageg5559m s_hiv6064w   s_ageg6064w  s_hiv6064m   s_ageg6064m    
s_inf_vlsupp  s_inf_newp  s_inf_ep  s_inf_diag  s_inf_naive  s_inf_primary s_birth_with_inf_child  
s_give_birth_with_hiv s_diag  s_diag_m s_diag_w s_diag_m1519_ s_diag_m2024_  s_diag_w1519_ s_diag_w2024_ s_diag_sw s_ai_naive_no_pmtct_c_nnm_  
s_ai_naive_no_pmtct_ s_ai_naive_no_pmtct_c_pim_ s_ai_naive_no_pmtct_c_rt184m_ s_ai_naive_no_pmtct_c_rt65m_  s_ai_naive_no_pmtct_c_rttams_ 
s_ai_naive_no_pmtct_e_inm_ s_artexp s_onart_iicu s_onart_w s_onart_m s_onart_sw  s_onartvisit0 s_onartvisit0_vl1000  s_onart_w  s_onart_m  
s_nactive_art_start_lt2  s_art_start s_nactive_art_start_lt3  s_nactive_art_start_lt1p5  s_efa s_taz s_ten s_zdv  s_dol  s_3tc  s_lpr  s_nev  s_tle 
s_tld s_zld  s_zla  s_otherreg s_o_zdv_tox s_o_3tc_tox s_o_ten_tox s_o_taz_tox s_o_lpr_tox s_o_efa_tox s_o_nev_tox s_o_dol_tox s_o_tle_tox 
s_o_tld_tox s_o_zld_tox s_o_zla_tox  s_o_zdv_adh_hi  s_o_3tc_adh_hi s_o_ten_adh_hi  s_o_taz_adh_hi  s_o_lpr_adh_hi s_o_efa_adh_hi s_o_nev_adh_hi 
s_o_dol_adh_hi  s_o_tle_adh_hi s_o_tld_adh_hi  s_o_zld_adh_hi  s_o_zla_adh_hi  s_adh_hi  s_u_vfail1_this_period s_u_vfail1 
s_k65m_  s_m184m_  s_vlg1000_184m s_vg1000 s_vlg1000_65m s_vlg1000_184m  s_vlg1000_65m s_vlg1000_onart_65m s_vlg1000_onart_184m  s_vlg1000_184m_ontle  
s_vlg1000_tams_ontle s_vlg1000_65m_ontle  s_vlg1000_ontle s_vlg1000_nnm_ontle s_vlg1000_184m_ontld  s_vlg1000_ontld s_vlg1000_tams_ontld  
s_vlg1000_65m_ontld  s_vlg1000_nnm_ontld s_vlg1000_inm_ontld s_nac_ge2p75_a_zld_if_reg_op_116 s_onart_start_zld_if_reg_op_116  
s_nac_ge2p00_a_zld_if_reg_op_116 s_nac_ge1p50_a_zld_if_reg_op_116 s_adh_hi_a_zld_if_reg_op_116 s_adh_hi_a_zld_if_reg_op_116 s_adh_hi_a_zld_if_reg_op_116 
s_e_rt65m_st_zld_if_reg_op_116  s_startedline2 s_onart_cd4_g500 s_onart_iicu s_onart_cl200  s_drug_level_test s_linefail_ge1  s_startedline2  
s_vl1000_art_gt6m_iicu  s_vg1000 s_vg1000_m s_vg1000_w  s_vg1000_m_1524 s_vg1000_w_1524 s_vl1000_art_gt6m_iicu_w  
s_onart_gt6m_iicu_w  s_vl1000_art_gt6m_iicu_m  s_onart_gt6m_iicu_m  s_vl1000_art_gt6m_iicu_1524_ s_onart_gt6m_iicu_1524_ s_vl1000_art_gt6m_iicu_sw   
s_onart_gt6m_iicu_sw  s_vl1000_art_12m  s_art_12m  s_vl1000_art_12m_onart  s_art_12m_onart  s_onart_m1549_  
s_onart_w1549_    s_vg1000  s_vg1000_1549 s_i_m_newp  s_i_vl1000_m_newp   s_i_vl1000_w_newp s_r_efa 
s_o_dol_2nd_vlg1000_dolr1_adh0 s_o_dol_2nd_vlg1000  s_o_dol_2nd_vlg1000_dolr1_adh1 s_o_dol_2nd_vlg1000_dolr0_adh0 s_o_dol_2nd_vlg1000_dolr0_adh1 
s_iime_  s_pime_  s_nnme_  s_death_hivrel  s_dead_onart s_dead_artexp  s_death_hiv 
s_death_hiv_m  s_death_hiv_w s_dead_hivpos_cause1 s_dead_hivpos_cause1 s_dead_hivpos_tb  s_dead_hivpos_cause4  s_dead_hivpos_crypm  s_dead_hivpos_sbi 
s_dead_hivpos_oth_adc s_dead_hivpos_cause2 s_dead_hivpos_cause3 s_dead_hivpos_cvd s_dead_cvd s_dead_tb  s_dead_hivneg_cvd s_dead_hivneg_tb  
s_dead_hivneg_cause2 s_dead_hivneg_cause3  s_dead_hivneg_cause4  s_dead_hivneg_cause5 s_dead_hivneg_anycause s_dead_cvd_3039m 
s_dead_cvd_4049m s_dead_cvd_5059m s_dead_cvd_6069m s_dead_cvd_7079m s_dead_cvd_ge80m s_dead_cvd_3039w s_dead_cvd_4049w s_dead_cvd_5059w s_dead_cvd_6069w 
s_dead_cvd_7079w s_dead_cvd_ge80w s_dead  s_covid  s_dead_hivneg_anycause  s_dead_hivpos_anycause s_dead2024m_all 
s_dead2529m_all s_dead3034m_all s_dead3539m_all s_dead4044m_all s_dead4549m_all s_dead5054m_all s_dead5559m_all s_dead2024w_all s_dead2529w_all 
s_dead3034w_all s_dead3539w_all s_dead4044w_all s_dead4549w_all s_dead5054w_all s_dead5559w_all s_cd4_g1  s_cd4_g2  s_cd4_g3 s_cd4_g1 s_art_initiation  
s_restart s_line1_fail_this_period  s_give_birth_with_hiv  s_birth_with_inf_child s_pregnant_ntd  s_pregnant_oth_dol_adv_birth_e s_onart_gt6m_iicu

/* parameters */
sex_beh_trans_matrix_m sex_beh_trans_matrix_w sex_age_mixing_matrix_m sex_age_mixing_matrix_w p_rred_p
p_hsb_p newp_factor eprate conc_ep ch_risk_diag ch_risk_diag_newp
ych_risk_beh_newp ych2_risk_beh_newp ych_risk_beh_ep exp_setting_lower_p_vl1000
external_exp_factor rate_exp_set_lower_p_vl1000 prob_pregnancy_base fold_change_w
fold_change_yw fold_change_sti tr_rate_undetec_vl super_infection_pop  super_inf_res  an_lin_incr_test
date_test_rate_plateau rate_testanc_inc incr_test_rate_sympt max_freq_testing
test_targeting fx gx adh_pattern prob_loss_at_diag pr_art_init 
rate_lost prob_lost_art rate_return rate_restart rate_int_choice
clinic_not_aw_int_frac res_trans_factor_nn rate_loss_persistence incr_rate_int_low_adh
poorer_cd4rise_fail_nn poorer_cd4rise_fail_ii rate_res_ten
fold_change_mut_risk adh_effect_of_meas_alert pr_switch_line prob_vl_meas_done
red_adh_tb_adc red_adh_tox_pop add_eff_adh_nnrti altered_adh_sec_line_pop
prob_return_adc prob_lossdiag_adctb prob_lossdiag_non_tb_who3e higher_newp_less_engagement
fold_tr fold_tr_newp switch_for_tox  
circ_inc_rate p_hard_reach_w hard_reach_higher_in_men
p_hard_reach_m inc_cat  base_rate_sw base_rate_stop_sexwork    rred_a_p
rr_int_tox   nnrti_res_no_effect  double_rate_gas_tox_taz   
incr_mort_risk_dol_weightg  sw_init_newp sw_trans_matrix
zero_tdf_activity_k65r  zero_3tc_activity_m184  red_adh_multi_pill_pop   greater_disability_tox	  greater_tox_zdv

effect_visit_prob_diag_l  tb_base_prob_diag_l crypm_base_prob_diag_l tblam_eff_prob_diag_l  crag_eff_prob_diag_l sbi_base_prob_diag_l
rel_rate_death_tb_diag_e rel_rate_death_oth_adc_diag_e rel_rate_death_crypm_diag_e  rel_rate_death_sbi_diag_e
incr_death_rate_tb incr_death_rate_oth_adc incr_death_rate_crypm incr_death_rate_sbi  cm_1stvis_return_vlmg1000  
crag_cd4_l200 crag_cd4_l100  tblam_cd4_l200  tblam_cd4_l100    effect_tb_proph   effect_crypm_proph  effect_sbi_proph

effect_sw_prog_prep_any  prob_prep_any_restart_choice 
adh_pattern_prep_oral   rate_test_startprep_any    rate_choose_stop_prep_oral
prep_any_strategy   prob_prep_any_visit_counsel  rate_test_onprep_any    
prob_prep_any_restart_choice  
pr_prep_oral_b  rel_prep_oral_adh_younger prep_oral_efficacy    
higher_future_prep_oral_cov  pr_prep_inj_b  prep_inj_efficacy
rate_choose_stop_prep_inj   prep_inj_effect_inm_partner  res_trans_factor_ii
rel_pr_inm_inj_prep_tail_primary      rr_res_cab_dol  hivtest_type_1_init_prep_inj   hivtest_type_1_prep_inj
sens_ttype1_prep_inj_primary sens_ttype1_prep_inj_inf3m sens_ttype1_prep_inj_infge6m
sens_ttype3_prep_inj_primary sens_ttype3_prep_inj_inf3m sens_ttype3_prep_inj_infge6m

effect_sw_prog_prep_any prob_prep_any_restart_choice dol_higher_potency  cab_time_to_lower_threshold_g
sens_tests_prep_inj  pr_inm_inj_prep_primary
pref_prep_inj_beta_s1  testt1_prep_inj_eff_on_res_prim  incr_res_risk_cab_inf_3m  reg_option_107_after_cab

p_emerge_inm_res_cab_notpr

rr_return_pop_wide_tld rr_interrupt_pop_wide_tld  prob_tld_if_untested  prob_onartvis0_0_to_1 prob_onartvis0_1_to_0

pref_prep_oral_beta_s1  res_level_dol_cab_mut  pr_res_dol prob_prep_pop_wide_tld  inc_oral_prep_pref_pop_wide_tld

prep_dependent_prev_vg1000   prep_vlg1000_threshold   prop_pep pep_efficacy artvis0_lower_adh pop_wide_prep_adh_effect 
low_prep_inj_uptake pop_wide_tld_selective_hiv  death_r_iris_pop_wide_tld  rr_mort_tdf_prep
prob_test_pop_wide_tld_prep
 ;


