#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=24:00:00
#$ -pe smp 4
#$ -t 1
#$ -A HIVSynthMod
#$ -l mem=6G
#$ -j y
#$ -N output
#$ -wd /home/rmjlaph/Scratch
#$ -o /dev/null
#$ -e /dev/null
#$ -l tmpfs=100G
module load sas/9.4/64
cd $TMPDIR
for file in `echo $addinfiles | tr ':' ' '` 
do 
 cp $file . 
done
sas $sas_infile
tar cvzf $HOME/Scratch/sv_$JOB_ID.tgz $TMPDIR


