#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=03:00:00
#$ -pe smp 4
#$ -t 1-1000
#$ -P Myriad
#$ -l mem=6G
#$ -j y
#$ -N unified
#$ -wd /home/rmjlaph/Scratch
#$ -o /dev/null
#$ -e /dev/null
module load sas/9.4/64
for file in `echo $addinfiles | tr ':' ' '` 
do 
 cp $file . 
done
mkdir -p work-$JOB_ID/$SGE_TASK_ID
sas -work work-$JOB_ID/$SGE_TASK_ID  $sas_infile
