#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=24:00:00
#$ -pe smp 4
#$ -t 1-1000
#$ -P HIVSynthMod
#$ -P Myriad
#$ -l mem=6G
#$ -j y
#$ -N unified
#$ -wd /home/rmjlaph/Scratch
#$ -o /dev/null
#$ -e /dev/null
#$ -l tmpfs=100G
module load sas/9.4/64
cd $TMPDIR
for file in `echo $addinfiles | tr ':' ' '` 
do 
 cp $file . 
done
sas $sas_infile
